version: "3.9"

services:
  app:
    build: .
    container_name: bandhan_app
    volumes:
      - uploads_data:/var/www/html/writable/uploads
    restart: always
    mem_limit: 512m
    cpus: 0.5

volumes:
  uploads_data:
